[tool.black]
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \venv
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
)
'''
include = '\.pyi?$'
line-length = 100
target-version = ['py310']

[tool.pytest.ini_options]
addopts = "--doctest-modules --cov=src --cov-branch --cov-report=xml --cov-report=html --junitxml=junit.xml"
